base_url = "http://127.0.0.1:1111"
title = "Blog name"
description = "Personal blog"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
author = "Barlog M."
github = "barlog-m"
twitter = "barlog_m"
