name = "Gruvbox Zen"
description = "Minimalistic gruvbox blog theme"
license = "MIT"
homepage = "https://github.com/bhigginsuk/gruvbox-zen"
min_version = "0.12.0"

[extra]

[author]
name = "Benjamin Higgins"
homepage = "https://www.brhiggins.com/"
